project:
  type: manuscript

execute:
  freeze: true
  
format:
  html:
    toc: true
    comments: 
      hypothesis: true
    repo-url: https://github.com/cwickham/submission-quarto-lite-r
    code-links: [binder, repo]
  agu-pdf: default
  docx: default
  jats: default


  