project:
  type: manuscript
  
manuscript:
  meca-archive: true
  article: article.qmd

format:
  html:
    toc: true
    format-links: [agu-pdf, docx]
    comments: 
      hypothesis: true
    repo-url: https://github.com/quarto-dev/quarto-demo
    repo-actions: [edit, issue]    
  agu-pdf: default
  docx: default
  jats:
    notebook-subarticles: true



  